// Generated by CoffeeScript 1.8.0
'use strict';
angular.module('clickingGame', []).controller('RootCtrl', function($scope, $timeout, CanvasDrawing) {
  var dropImages, getXY;
  $scope.drops = 0;
  $scope.dropImgFiles = ['tint_1.png', 'tint_2.png', 'tint_3.png'];
  dropImages = [];
  $timeout(function() {
    return dropImages = $('.drops .drop');
  });
  getXY = function(event) {
    if (event.offsetX === null) {
      return {
        x: event.originalEvent.layerX,
        y: event.originalEvent.layerY
      };
    } else {
      return {
        x: event.offsetX,
        y: event.offsetY
      };
    }
  };
  return $scope.canvasClick = function($event) {
    var pt;
    pt = getXY($event);
    return _.times(10, function() {
      var size;
      size = _.normalRandom(40, 20);
      CanvasDrawing.addDrop({
        img: _.sample(dropImages, 1)[0],
        x: pt.x - size / 2,
        y: pt.y - size / 3,
        w: size,
        h: size,
        xspeed: _.normalRandom(0, 10),
        yspeed: _.normalRandom(-9, 6),
        yacceleration: 1
      });
      return $scope.drops++;
    });
  };
}).factory('CanvasDrawing', function() {
  var accumulator, animloop, canvas, ctx, currTime, drops, moveDrop, movedt, render;
  canvas = document.getElementById('canvas');
  ctx = new Context2DWrapper(canvas.getContext('2d'));
  drops = [];
  moveDrop = function(drop) {
    drop.y = drop.y + drop.yspeed;
    drop.yspeed = drop.yspeed + drop.yacceleration;
    drop.xspeed = drop.xspeed / 1.03;
    drop.x += drop.xspeed;
    return drop.y < 700;
  };
  movedt = 1000 / 60;
  accumulator = 0;
  currTime = 0;
  render = function(time) {
    var dt;
    dt = time - currTime;
    currTime = time;
    accumulator += dt;
    while (accumulator > movedt) {
      drops = _.filter(drops, moveDrop);
      accumulator -= movedt;
    }
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    _.each(drops, function(drop) {
      return ctx.drawImage(drop.img, drop.x, drop.y, drop.w, drop.h);
    });
    return console.log(drops.length, dt, time);
  };
  animloop = function(time) {
    requestAnimationFrame(animloop);
    return render(time);
  };
  animloop(0);
  return {
    addDrop: function(obj) {
      return drops.push(obj);
    }
  };
});

_.mixin({
  normalRandom: function(middle, delta) {
    var max, min, _ref;
    _ref = [middle - delta, middle + delta], min = _ref[0], max = _ref[1];
    return (_.random(min, max) + _.random(min, max) + _.random(min, max)) / 3;
  }
});
