// Generated by CoffeeScript 1.8.0
'use strict';
angular.module('clickingGame', []).controller('RootCtrl', function($scope, $timeout, CanvasDrawing) {
  var dropImages, getXY;
  $scope.drops = 0;
  $scope.dropImgFiles = ['tint_1.png', 'tint_2.png', 'tint_3.png'];
  dropImages = [];
  $timeout(function() {
    return dropImages = $('.drops .drop');
  });
  getXY = function(event) {
    if (event.offsetX === null) {
      return {
        x: event.originalEvent.layerX,
        y: event.originalEvent.layerY
      };
    } else {
      return {
        x: event.offsetX,
        y: event.offsetY
      };
    }
  };
  return $scope.canvasClick = function($event) {
    var pt;
    pt = getXY($event);
    return _.times(10000, function() {
      var size;
      size = _.random(20, 64);
      CanvasDrawing.addDrop({
        img: _.sample(dropImages, 1)[0],
        x: pt.x - size / 2,
        y: pt.y - size / 3,
        w: size,
        h: size,
        xacceleration: _.random(-3, 3) + _.random(-3, 3) + _.random(-3, 3),
        yacceleration: _.random(-15, -3)
      });
      return $scope.drops++;
    });
  };
}).factory('CanvasDrawing', function() {
  var animloop, canvas, ctx, drops, moveDrop, prevTime, render;
  canvas = document.getElementById('canvas');
  ctx = new Context2DWrapper(canvas.getContext('2d'));
  drops = [];
  moveDrop = function(drop) {
    ctx.drawImage(drop.img, drop.x, drop.y, drop.w, drop.h);
    drop.yacceleration += 1;
    drop.y += drop.yacceleration;
    drop.xacceleration /= 1.03;
    drop.x += drop.xacceleration;
    return drop.y < 700;
  };
  prevTime = 0;
  render = function(time) {
    var timeDiff;
    timeDiff = time - prevTime;
    prevTime = time;
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    drops = _.filter(drops, moveDrop);
    return console.log(drops.length, timeDiff, time);
  };
  animloop = function(time) {
    requestAnimationFrame(animloop);
    return render(time);
  };
  animloop(0);
  return {
    addDrop: function(obj) {
      return drops.push(obj);
    }
  };
});
